### ISSUE TITLE
Erro - simplexml_load_string()

### ISSUE THREAD

**Issue by Hatalias** [angelodmrch/pagseguro#1]
Estou com esse erro, alguém sabe porque?"simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found" on line 277 of D:\wamp64\www\promo\plugins\dmrch\pagseguro\components\Pagseguro.php

**Comment by angelodmrch** [comment]
Olá @Hatalias. Qual a versão do October que você esta usando e quando exatamente o erro ocorre?

**Comment by angelodmrch** [comment]
@Hatalias , O que tudo indica que é a requisição na função onGetSession() do arquivo components\Pagseguro.php não esta retornando um XML, verifique se as tuas credencias chegam certar ali

**Comment by Hatalias** [comment]
Versão 1, logo quando acessa no index, ja aparece essa msg

Em qui., 26 de jan. de 2023 às 15:58, Angelo Demarchi <
***@***.***> escreveu:

**Comment by Hatalias** [comment]
Eu instalei seu plugin para ajustar ao meu projeto.
Quanto voce me cobraria para fazer essa implementação?
eu preciso fazer um formulário para a pessoa colocar os dados dela (nome,
tel...) e os dados do cartão, fez o pagamento do valor x (fixo) ele cria um
registro no backend com os dados e a confirmação de pagamento do pagseguro
ai o resto eu ajusto aqui

Em qui., 26 de jan. de 2023 às 16:24, Hatalias ***@***.***>
escreveu:
